services:
  order-db:
    image: mariadb:11.5.2
    container_name: order-db
    env_file: ./apps/order/.env
    ports:
      - '${ORDER_DB_PORT:-3306}:3306'
    volumes:
      - order_db:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u$$MARIADB_USER', '-p$$MARIADB_PASSWORD']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  auth-db:
    image: mariadb:11.5.2
    container_name: auth-db
    env_file: ./apps/auth/.env
    ports:
      - '${AUTH_DB_PORT:-3307}:3306'
    volumes:
      - auth_db:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u$$MARIADB_USER', '-p$$MARIADB_PASSWORD']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
volumes:
  order_db:
  auth_db:
