services:
  api-db:
    image: mariadb:11.5.2
    container_name: api-db
    env_file: ./apps/api/.env
    ports:
      - '3306:3306'
    volumes:
      - api_db:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u$$MARIADB_USER', '-p$$MARIADB_PASSWORD']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  auth-db:
    image: mariadb:11.5.2
    container_name: auth-db
    env_file: ./apps/auth/.env
    ports:
      - '3307:3306'
    volumes:
      - auth_db:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u$$MARIADB_USER', '-p$$MARIADB_PASSWORD']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
volumes:
  api_db:
  auth_db:
